export const DEFAULT_COLS = 80;
export const DEFAULT_ROWS = 25;
export const DEFAULT_FG = 7;
export const DEFAULT_BG = 0;
export const DEFAULT_DIALOG_WIDTH = 40;
export const SCROLLBACK_MAX = 2000;
// Scrollback is trimmed in batches so line feeds avoid an O(N) shift() per row.
export const SCROLLBACK_TRIM_SLACK = 256;
export const CHAR_WIDTH = 8;
export const CHAR_HEIGHT = 16;
export const TAB_WIDTH = 8;
export const CSI_INTRODUCER = 0x5B;

export const ESC = 0x1B;
export const ESC_OSC = 0x5D;
export const ESC_DCS = 0x50;
export const ESC_SOS = 0x58;
export const ESC_PM = 0x5E;
export const ESC_APC = 0x5F;
export const ESC_IND = 0x44;
export const ESC_NEL = 0x45;
export const ESC_SAVE = 0x37;
export const ESC_RESTORE = 0x38;
export const ESC_TABSET = 0x48;
export const ESC_RI = 0x4D;
export const ESC_ST = 0x5C;
export const BEL = 0x07;
export const CR = 0x0D;
export const LF = 0x0A;
export const BS = 0x08;
export const TAB = 0x09;
export const DEL = 0x7F;   // delete — ignored, never printed
export const CAN = 0x18;   // cancel: aborts an in-progress CSI/DCS string
export const SUB = 0x1A;
export const MOUSE_EVENT_MODES = Object.freeze([1000, 1002, 1003]);
export const MOUSE_SGR = 1006;
export const ESC_SS2 = 0x4E;
export const ESC_SS3 = 0x4F;
